### ISSUE TITLE
calval trigger fails due to new token requirements

### ISSUE THREAD

**Issue by khufkens** [computationales/rsofun#103]
Old setup is documented here but a finely grained token is needed, but with what permissions is unclear.

```
on:
  push:
  workflow_dispatch:

name: render sofunCalVal repo

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{secrets.PAT_TOKEN}}
        run: |
          gh api repos/computationales/sofunCalVal/dispatches \
              --raw-field event_type=render
```
