### ISSUE TITLE
automatic deployment of documentation

### ISSUE THREAD

**Issue by khufkens** [computationales/rsofun#105]
```
on:
  push:
     branches:
       - main

name: deployblog

jobs:
  blogdown:
    name: Render-Blog
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","pkgdown","devtools"), repos = "http://cran.rstudio.com/")'
      - name: install theme
        run: Rscript -e 'devtools::install_github("computationales/GECO_template")'
      - name: Render blog
        run: Rscript -e 'pkgdown::build_site()'
      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: docs/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: blogdown
   steps:
     - name: Checkout
       uses: actions/checkout@main
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: public # optional
         # Destination path
         path: public # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       with:
        # build dir
        build_dir: public/
        email: koen.hufkens@gmail.com
        jekyll: no
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
```
